### ISSUE TITLE
Crash when clicking the lock on a page without a textbox

### ISSUE THREAD

**Issue by EndergamerHUN** [TaiAurori/channel-locker#2]
When you click any of the lock buttons for the first time opening up discord, it will crash. This does not happen after you have opened any page with a chatbox (or at least not that I could produce).

Here is a video of it:
https://user-images.githubusercontent.com/67326262/124515852-bb511c80-dde0-11eb-8cf3-136bad67ba47.mp4

**Comment by TaiAurori** [comment]
pushed a fix, *hopefully* it no longer displays the buttons on pages with no channel id

**Comment by TaiAurori** [comment]
(it would be helpful if you could close this issue if the bug is resolved)
